### ISSUE TITLE
打破零 issue

### ISSUE THREAD

**Issue by clsty** [skyone-wzw/nginx-autoindex#1]
简单评价一下：

跟 [miniserve](https://github.com/svenstaro/miniserve) 的定位很像，同时又完全不需要运行额外服务，只是利用 nginx 的 autoindex，又不像原生的 autoindex 那么简陋。
我还是挺喜欢这种设计的——怎么说呢，就像那种不需要外接供电，只要插在主板上就行的显卡一样，有种莫名的美感。

一点建议：
- nginx 的那个模板：
  - “记得改”不够具体，虽然据上下文也大概能猜出来是改成刚才解压 nginx-autoindex.zip 到的目录。
  - 实测 server 块里要加 `charset utf-8;` 否则中文会乱码（可能在 windows 上不会？我的 nginx 是运行在 Linux 上）。
- 希望能添加如何从 Git 仓库构建的说明，类似于 <https://github.com/clsty/arCNiso/blob/main/docs/BUILD.md>。我个人认为对于开源项目，这个还是比较重要的。

ps. 已给 star。这个也算是你给我的 [arCNiso](https://github.com/clsty/arCNiso) 的 star 的回礼，很高兴时隔许久又有人来光顾我那个小项目了。谢谢你！

**Comment by skyone-wzw** [comment]
感谢你的意见！我会尽快进行一些修改。

* 确实没有考虑到 `charset` 的问题，也不知道为什么当初运行没问题。
* 构建很简单，只要 `npm install` 加 `npm run build` 就行了，当然你说的很对，我会马上添加构建的说明。

当初我准备写这个小程序的时候其实是想aria2下番，在线看😋。也没多想，就怎么简单怎么来。运行起来后发现效果还行，反正写都写了，就放到github上了。期间也考虑过更好的优化这个小程序，比如：使用 nginx 的 `ngx_http_xslt_module` 模块直接将 nginx 生成的 xml 转换成网页，而不是现在的解析字符串并使用 react 渲染。但遗憾的是 nginx 默认不包含 xslt 模块，为了这个自己编译 nginx 显然是不值得的。

最初的目标已经实现了，再加上我本身专业和计算机毫无关联，搞这些纯属兴趣，之后就没动过这个仓库了。没想到这种代码也能收到star（至少过了半年我再看这代码简直不堪入目😱）。

> 题外话：其实很羡慕想你们这样有想法又能通过努力实现的人，就比如[arCNiso](https://github.com/clsty/arCNiso)，我在一次意外翻到 [archiso wiki](https://wiki.archlinux.org/title/Archiso) 时也想能不能自己定制一个 linux live cd，但奈何终究不是计算机相关专业，时间上又不允许我详细的了解那些对大多数开发者可能很基础的知识，而且让我写点小程序还行，工程量稍大一点就不行了，最后只能作罢。
>
> 不过反过来想，就把编程作为一项业余爱好，用到哪学到哪，没有任何负担，做自己感兴趣的事，好像也还不错？

**Comment by clsty** [comment]
> 没想到这种代码也能收到star（至少过了半年我再看这代码简直不堪入目😱）。

~没关系，我又不懂 js~ 我是从用户的角度来给 star 的，使用体验还行，所以还请你安心地接受吧 :p

> 我在一次意外翻到 [archiso wiki](https://wiki.archlinux.org/title/Archiso) 时也想能不能自己定制一个 linux live cd，但奈何终究不是计算机相关专业，时间上又不允许我详细的了解那些对大多数开发者可能很基础的知识，而且让我写点小程序还行，工程量稍大一点就不行了，最后只能作罢。

你也可以基于 arCNiso 来定制 archiso，有问题欢迎来 arCNiso 的 [Discussions](https://github.com/clsty/arCNiso/discussions) 提问讨论。我也一直想完善[“如何定制”](https://github.com/clsty/arCNiso/blob/main/docs/update.md)方面的文档，奈何不知从何说起（笑），主要是此项目也是一点点拼凑出来的，虽然各个部分单独拿出来说我还是能做到的，但要整理成流程的话我已经不记得当初的顺序了。
如果你想定制 arCNiso，可以先试着不作改动直接[构建](https://github.com/clsty/arCNiso/blob/main/docs/BUILD.md)一次，成功了之后再修改，并再次构建。
实际上 arCNiso 当初也是个简单的项目，后面是不断迭代才发展为现在这样的。我觉得即使是大项目，只要把目标拆解开，其中的每一步也不过是个小项目罢了。
定制 arCNiso 与使用 Arch Linux 所需的知识也有很大部分的重合，大部分靠 ArchWiki；（半）自动化主要靠 Bash 脚本来实现，哪里不会查哪里，况且 shell 每天都在接触。总之，也并没有什么特别需要额外学习的基础。

**Comment by skyone-wzw** [comment]
经过一定修改, 目前已经实现了:

* 尽可能减少加载时屏幕闪烁
* 进入文件夹不需要重载网页
* docker 及 docker-compose
* 实现了 github 最新的 [blockquote语法](https://github.com/orgs/community/discussions/16925)

demo 移动到了 [https://nginx-autoindex-demo.skyone.host/](https://nginx-autoindex-demo.skyone.host/)

此 issue 已经解决，再次感谢你的建议，有任何问题欢迎再提 issue！
