### ISSUE TITLE
文件显示排序

### ISSUE THREAD

**Issue by jhl-hk** [skyone-wzw/nginx-autoindex#2]
文件夹是否可以以倒叙的方式显示

**Comment by skyone-wzw** [comment]
你好：

在文件夹数量较多时，对文件夹的排序确实比较有用，我会尽快实现这个功能。

设计之初我其实没有考虑到文件夹的排序（因为当时主要是为了看番），所以排序的逻辑写的很乱，我会尝试整理一下的。

我可能会实现：

- 文件夹的排序
- 选择文件夹是否参与文件的排序
- 按文件类型排序

并添加一个以上功能的开关界面

谢谢你的建议！

**Comment by skyone-wzw** [comment]
既定目标已经完成！

- [x] 文件夹的排序
- [x] 选择文件夹是否参与文件的排序
- [x] 按文件类型排序

功能包含在 [v1.2.1](https://github.com/skyone-wzw/nginx-autoindex/releases/tag/v1.2.1) 中。

此 issue 已经解决，如有以上功能的问题可以再次回复此 issue，有任何其他问题欢迎再提新 issue！
