### ISSUE TITLE
项目部署后无法显示文件大小及文件上传时间

### ISSUE THREAD

**Issue by stevn-kin** [skyone-wzw/nginx-autoindex#3]
项目部署后无法显示文件大小及文件上传时间，您部署后会正常显示吗？

**Comment by skyone-wzw** [comment]
您好，示例网站使用的就是latest release，您没有提供更多信息，我也不知道出了什么问题。如果您愿意，可以试着排查一下

这个程序的原理是在Nginx生成的页面后面加上一个JavaScript脚本，解析原本的页面并生成新的页面。如果部署后无法显示文件大小及文件上传时间，可能是原本Nginx生成的页面不符合预期。

可以试试暂时禁用本美化程序，具体方法是把下面的这一行nginx配置文件注释掉：

```nginx
add_after_body /autoindex.html;
# "#"后为注释
```

让nginx重新加载配置文件，打开页面观察一下nginx生成的页面是否包含大小和上传时间，页面应该类似这样：

![image](https://github.com/skyone-wzw/nginx-autoindex/assets/73385177/6ab548e8-5a36-42b5-8b28-26efd002ef93)

**Comment by stevn-kin** [comment]
好的，感谢你的回复，我尽快排查一下原因。

**Comment by stevn-kin** [comment]
您好，
1. 文件名称是中文的时候控制台报错，并且会推出到默认的界面。
2. 文件大于1MB时会只显示文件名，修改时间与文件大小无法显示，控制台输出这两个值是NULL。

**Comment by skyone-wzw** [comment]
您好，根据您提供的信息，我尝试复现问题。

我使用了多个大于1MB的文件，但是在我这里没有复现问题（我使用的是docker容器，nginx配置文件见 [docker/default.conf](https://github.com/skyone-wzw/nginx-autoindex/blob/v1.2.1/docker/default.conf)）

![image](https://github.com/skyone-wzw/nginx-autoindex/assets/73385177/61af33e1-01dc-49bb-a6e8-00a2d975e97d)

您可以重点检查以下nginx配置：

* `server` 块是否包含 `charset utf-8;`
* `autoindex_localtime` 的值为 `off` （默认为 `off`）
* `autoindex_format` 的值为 `html` （默认就是 `html`）
* `autoindex_exact_size` 为 `on` （同样是默认）

根据您给出的信息我只能做到这一步，如果还是有问题，您需要提供更信息的信息（如nginx返回的响应体或一个最小可复现示例）。

当然，您也可以选择使用容器或根据[docker/default.conf](https://github.com/skyone-wzw/nginx-autoindex/blob/v1.2.1/docker/default.conf)修改。

**Comment by stevn-kin** [comment]
您好，根据您最新的回复:
- autoindex_localtime 的值为 off （默认为 off）
- autoindex_format 的值为 html （默认就是 html）
- autoindex_exact_size 为 on （同样是默认）
将这三个参数配置为了默认值，现已配置成功，感谢您的回复。XD

**Comment by skyone-wzw** [comment]
好的👌

此 issue 已经解决，如有以上功能的问题可以再次回复此 issue，有任何其他问题欢迎再提新 issue！

**Comment by stevn-kin** [comment]
COPY :)
